/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the owner's timezone and recurring weekly availability rules. */
        get: operations["getAvailability"];
        /** @description Replaces the full recurring availability configuration for the owner. */
        put: operations["replaceAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/availability-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns all concrete availability overrides configured by the owner. */
        get: operations["listAvailabilityOverrides"];
        put?: never;
        /** @description Creates a concrete availability override for a specific UTC interval. */
        post: operations["createAvailabilityOverride"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/availability-overrides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Deletes one availability override by its internal identifier. */
        delete: operations["deleteAvailabilityOverride"];
        options?: never;
        head?: never;
        /** @description Updates one availability override by its internal identifier. */
        patch: operations["updateAvailabilityOverride"];
        trace?: never;
    };
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the owner's bookings for admin review. */
        get: operations["listAdminBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns all event types, including inactive ones, for the admin panel. */
        get: operations["listAdminEventTypes"];
        put?: never;
        /** @description Creates a new event type managed by the owner. */
        post: operations["createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Deletes an event type by its internal identifier. */
        delete: operations["deleteEventType"];
        options?: never;
        head?: never;
        /** @description Updates an existing event type by its internal identifier. */
        patch: operations["updateEventType"];
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns all active public event types that a guest can choose from. */
        get: operations["listPublicEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the public details for one event type identified by its slug. */
        get: operations["getPublicEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{slug}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates a booking for the selected event type and start time.
         *
         *     The event type is identified by the public slug in the route.
         *     The backend derives the final booking interval from the event type duration.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns computed available slots for the next 14 days for the selected event type. */
        get: operations["listEventTypeSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a lightweight health response for uptime and connectivity checks. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Full recurring availability configuration used by the admin panel. */
        AvailabilityConfiguration: {
            /** @description Canonical owner timezone used to interpret weekly rules. */
            timezone: components["schemas"]["IanaTimeZone"];
            /** @description Recurring weekly availability rules. */
            weeklyRules: components["schemas"]["WeeklyAvailabilityRule"][];
        };
        /** @description Concrete availability exception applied to a specific UTC interval. */
        AvailabilityOverride: {
            /** @description Internal technical identifier. */
            id: string;
            /**
             * Format: date-time
             * @description Inclusive start of the overridden UTC interval.
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description Exclusive end of the overridden UTC interval.
             */
            endUtc: string;
            /** @description Whether the interval is explicitly available or blocked. */
            isAvailable: boolean;
        };
        /** @description Confirmed booking created by a guest for a concrete UTC interval. */
        Booking: {
            /** @description Internal technical identifier. */
            id: string;
            /** @description Internal identifier of the booked event type. */
            eventTypeId: string;
            /** @description Guest name provided during booking. */
            guestName: string;
            /** @description Guest email used for contact and confirmation flows. */
            guestEmail: components["schemas"]["EmailAddress"];
            /** @description Optional note left by the guest. */
            guestNotes?: string;
            /**
             * Format: date-time
             * @description Inclusive booking start in UTC.
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description Exclusive booking end in UTC, computed from the event type duration.
             */
            endUtc: string;
            /**
             * Format: date-time
             * @description Timestamp when the booking was created.
             */
            createdAt: string;
        };
        /** @description Returned when the request conflicts with the current state of the system. */
        ConflictError: {
            /**
             * @description Stable machine-readable error code.
             * @enum {string}
             */
            code: "conflict";
            /** @description Human-readable error message. */
            message: string;
        };
        /** @description Request payload used to create a concrete availability override. */
        CreateAvailabilityOverrideRequest: {
            /**
             * Format: date-time
             * @description Inclusive start of the overridden UTC interval.
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description Exclusive end of the overridden UTC interval.
             */
            endUtc: string;
            /** @description Whether the interval is explicitly available or blocked. */
            isAvailable: boolean;
        };
        /** @description Request payload used to create a booking for a public event type. */
        CreateBookingRequest: {
            /**
             * Format: date-time
             * @description Selected booking start time in UTC.
             */
            startUtc: string;
            /** @description Guest name provided during booking. */
            guestName: string;
            /** @description Guest email used for contact and confirmation flows. */
            guestEmail: components["schemas"]["EmailAddress"];
            /** @description Optional note left by the guest. */
            guestNotes?: string;
        };
        /** @description Request payload used to create a new event type. */
        CreateEventTypeRequest: {
            /** @description Display name shown to guests and in the admin panel. */
            title: string;
            /** @description Optional public description of the meeting type. */
            description?: string;
            /**
             * Format: int32
             * @description Duration of the meeting in minutes.
             */
            durationMinutes: number;
            /** @description Whether guests can book the event type immediately after creation. */
            isActive?: boolean;
        };
        /** @description Response returned after successfully creating an availability override. */
        CreatedAvailabilityOverrideResponse: {
            /** @description Newly created availability override resource. */
            availabilityOverride: components["schemas"]["AvailabilityOverride"];
        };
        /** @description Response returned after successfully creating a booking. */
        CreatedBookingResponse: {
            /** @description Newly created booking resource. */
            booking: components["schemas"]["Booking"];
        };
        /** @description Response returned after successfully creating an event type. */
        CreatedEventTypeResponse: {
            /** @description Newly created event type resource. */
            eventType: components["schemas"]["EventType"];
        };
        /**
         * @description Day of week used by recurring weekly availability rules.
         * @enum {string}
         */
        DayOfWeek: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
        /**
         * Format: email
         * @description Guest email address used for booking contact details.
         */
        EmailAddress: string;
        /** @description Administrative representation of a bookable meeting type. */
        EventType: {
            /** @description Internal technical identifier. */
            id: string;
            /** @description Public human-readable identifier used in URLs. */
            slug: components["schemas"]["Slug"];
            /** @description Display name shown to guests and in the admin panel. */
            title: string;
            /** @description Optional public description of the meeting type. */
            description?: string;
            /**
             * Format: int32
             * @description Duration of the meeting in minutes.
             */
            durationMinutes: number;
            /** @description Whether guests can currently book this event type. */
            isActive: boolean;
            /**
             * Format: date-time
             * @description Timestamp when the event type was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the event type was last updated.
             */
            updatedAt: string;
        };
        /** @description IANA timezone name used to interpret recurring availability rules. */
        IanaTimeZone: string;
        /** @description Returned when the requested resource does not exist. */
        NotFoundError: {
            /**
             * @description Stable machine-readable error code.
             * @enum {string}
             */
            code: "not_found";
            /** @description Human-readable error message. */
            message: string;
        };
        /** @description Full public representation of a single bookable event type. */
        PublicEventType: components["schemas"]["PublicEventTypeSummary"];
        /** @description Lightweight public view of a bookable event type. */
        PublicEventTypeSummary: {
            /** @description Public human-readable identifier used in URLs. */
            slug: components["schemas"]["Slug"];
            /** @description Display name shown to guests. */
            title: string;
            /** @description Optional public description of the meeting type. */
            description?: string;
            /**
             * Format: int32
             * @description Duration of the meeting in minutes.
             */
            durationMinutes: number;
        };
        /** @description Request payload used to replace the full recurring availability configuration. */
        ReplaceAvailabilityRequest: {
            /** @description Canonical owner timezone used to interpret weekly rules. */
            timezone: components["schemas"]["IanaTimeZone"];
            /** @description Full set of recurring weekly rules that replaces the current configuration. */
            weeklyRules: components["schemas"]["WeeklyAvailabilityRuleInput"][];
        };
        /** @description Computed bookable time range returned by the public booking flow. */
        Slot: {
            /**
             * Format: date-time
             * @description Inclusive slot start in UTC.
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description Exclusive slot end in UTC.
             */
            endUtc: string;
        };
        /** @description Public human-readable identifier used in URLs. */
        Slug: string;
        /** @description Request payload used to update a concrete availability override. */
        UpdateAvailabilityOverrideRequest: {
            /**
             * Format: date-time
             * @description Updated inclusive start of the overridden UTC interval.
             */
            startUtc?: string;
            /**
             * Format: date-time
             * @description Updated exclusive end of the overridden UTC interval.
             */
            endUtc?: string;
            /** @description Updated availability flag for the interval. */
            isAvailable?: boolean;
        };
        /** @description Request payload used to update an existing event type. */
        UpdateEventTypeRequest: {
            /** @description Updated display name shown to guests and in the admin panel. */
            title?: string;
            /** @description Updated optional public description of the meeting type. */
            description?: string;
            /**
             * Format: int32
             * @description Updated meeting duration in minutes.
             */
            durationMinutes?: number;
            /** @description Updated public availability flag. */
            isActive?: boolean;
        };
        /** @description Returned when the request payload or parameters fail validation. */
        ValidationError: {
            /**
             * @description Stable machine-readable error code.
             * @enum {string}
             */
            code: "validation_error";
            /** @description Human-readable error message. */
            message: string;
        };
        /** @description Recurring weekly rule that defines when the owner is available. */
        WeeklyAvailabilityRule: {
            /** @description Internal technical identifier. */
            id: string;
            /** @description Day of week for this recurring rule. */
            dayOfWeek: components["schemas"]["DayOfWeek"];
            /**
             * Format: time
             * @description Local start time in the owner's timezone.
             */
            startLocalTime: string;
            /**
             * Format: time
             * @description Local end time in the owner's timezone.
             */
            endLocalTime: string;
        };
        /** @description Input shape used to replace recurring weekly availability rules. */
        WeeklyAvailabilityRuleInput: {
            /** @description Day of week for this recurring rule. */
            dayOfWeek: components["schemas"]["DayOfWeek"];
            /**
             * Format: time
             * @description Local start time in the owner's timezone.
             */
            startLocalTime: string;
            /**
             * Format: time
             * @description Local end time in the owner's timezone.
             */
            endLocalTime: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityConfiguration"];
                };
            };
        };
    };
    replaceAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceAvailabilityRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityConfiguration"];
                };
            };
            /** @description Returned when the request payload or parameters fail validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    listAvailabilityOverrides: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityOverride"][];
                };
            };
        };
    };
    createAvailabilityOverride: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvailabilityOverrideRequest"];
            };
        };
        responses: {
            /** @description Response returned after successfully creating an availability override. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAvailabilityOverrideResponse"];
                };
            };
            /** @description Returned when the request payload or parameters fail validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    deleteAvailabilityOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returned when a delete operation succeeds without a response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Returned when the requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    updateAvailabilityOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvailabilityOverrideRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityOverride"];
                };
            };
            /** @description Returned when the request payload or parameters fail validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Returned when the requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    listAdminBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    listAdminEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description Response returned after successfully creating an event type. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedEventTypeResponse"];
                };
            };
            /** @description Returned when the request payload or parameters fail validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Returned when the request conflicts with the current state of the system. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returned when a delete operation succeeds without a response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Returned when the requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Returned when the request payload or parameters fail validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Returned when the requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Returned when the request conflicts with the current state of the system. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    listPublicEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventTypeSummary"][];
                };
            };
        };
    };
    getPublicEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventType"];
                };
            };
            /** @description Returned when the requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Response returned after successfully creating a booking. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedBookingResponse"];
                };
            };
            /** @description Returned when the request payload or parameters fail validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Returned when the requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Returned when the request conflicts with the current state of the system. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    listEventTypeSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Returned when the requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
}
